/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * SysTool API
 * API documentation cho SysTool backend
 * OpenAPI spec version: 1.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import { customInstance } from './mutator';
export interface PermissionDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface NumberWhereDto {
  /** Match any value in the list of Number */
  in?: number[];
  /** Exclude any value in the list of Number */
  notIn?: number[];
  /** Match any value in the list of Number */
  isNull?: boolean;
  /** Match any value in the list of Number */
  isNotNull?: boolean;
  /** Match numbers greater than this value */
  gt?: number;
  /** Match numbers less than this value */
  lt?: number;
  /** Match numbers greater than or equal to this value */
  gte?: number;
  /** Match numbers less than or equal to this value */
  lte?: number;
}

export interface DateWhereDto {
  /** Match any value in the list of Date */
  in?: string[];
  /** Exclude any value in the list of Date */
  notIn?: string[];
  /** Match any value in the list of Date */
  isNull?: boolean;
  /** Match any value in the list of Date */
  isNotNull?: boolean;
  /** Match dates greater than this value */
  gt?: string;
  /** Match dates greater than or equal to this value */
  gte?: string;
  /** Match dates less than this value */
  lt?: string;
  /** Match dates less than or equal to this value */
  lte?: string;
}

export interface BooleanWhereDto {
  /** Match any value in the list of Boolean */
  in?: boolean[];
  /** Exclude any value in the list of Boolean */
  notIn?: boolean[];
  /** Match any value in the list of Boolean */
  isNull?: boolean;
  /** Match any value in the list of Boolean */
  isNotNull?: boolean;
}

export interface StringWhereDto {
  /** Match any value in the list of String */
  in?: string[];
  /** Exclude any value in the list of String */
  notIn?: string[];
  /** Match any value in the list of String */
  isNull?: boolean;
  /** Match any value in the list of String */
  isNotNull?: boolean;
  /** Search for strings containing this substring */
  contains?: string;
}

export interface PermissionDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  name?: StringWhereDto;
  description?: StringWhereDto;
  canDelete?: BooleanWhereDto;
}

/**
 * The type of the permission
 */
export type PermissionRelationsDtoUnitType =
  (typeof PermissionRelationsDtoUnitType)[keyof typeof PermissionRelationsDtoUnitType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionRelationsDtoUnitType = {
  add: 'add',
  remove: 'remove',
} as const;

export interface PermissionRelationsDtoUnit {
  type: PermissionRelationsDtoUnitType;
  /** The id of the parent permission */
  id: number;
}

export interface PermissionRelationsDto {
  /** The id of the permission */
  id: number;
  /** The parents of the permission */
  parents: PermissionRelationsDtoUnit[];
  /** The children of the permission */
  children: PermissionRelationsDtoUnit[];
}

export interface Permission {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  name: string;
  description: string;
  canDelete: boolean;
  parentIds: string[];
}

export interface PermissionDtoChildren {
  /** The id of the permission */
  id: number;
}

export interface PermissionDto {
  /** The id of the permission */
  id: number;
  /** The name of the permission */
  name: string;
  /** The description of the permission */
  description: string;
  /** The children of the permission */
  children: PermissionDtoChildren[];
}

export interface UserDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface UserDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  email?: StringWhereDto;
}

export interface User {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  email: string;
  permissions: Permission[];
  inventories: Inventory[];
}

export interface ItemType {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  name: string;
  description: string;
  symbol: string;
}

export interface Inventory {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  user: User;
  itemType: ItemType;
  quantity: number;
  expirationDate: string;
}

export interface UserPermissionDto {
  permissions?: PermissionDtoChildren[];
}

export type InventoriesUnitAction =
  (typeof InventoriesUnitAction)[keyof typeof InventoriesUnitAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InventoriesUnitAction = {
  add: 'add',
  remove: 'remove',
  set: 'set',
} as const;

export interface InventoriesUnitDto {
  action: InventoriesUnitAction;
  itemId: number;
  quantity: number;
  expirationDate?: string;
}

export interface UserInventoriesDto {
  inventories?: InventoriesUnitDto[];
}

export type BaseTrackingAction =
  (typeof BaseTrackingAction)[keyof typeof BaseTrackingAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BaseTrackingAction = {
  create: 'create',
  update: 'update',
  delete: 'delete',
} as const;

export interface ItemTypeDto {
  /** ID của loại vật phẩm */
  id?: number;
  /** Tên loại vật phẩm */
  name?: string;
  /** Mô tả loại vật phẩm */
  description?: string;
  /** Ký hiệu loại vật phẩm */
  symbol?: string;
}

export interface UserInvertoryDto {
  id?: number;
  quantity?: number;
  expirationDate?: string;
  itemType?: ItemTypeDto;
}

export interface UserInventoriesTrackingDto {
  action: BaseTrackingAction;
  data: UserInvertoryDto;
}

export interface UserDto {
  id?: number;
  email?: string;
}

export interface GoogleAuthDto {
  token: string;
}

export interface GoogleAuthResponseDto {
  accessToken: string;
}

export interface GetConfigDto {
  clientId: string;
}

export interface SysConfigDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface SysConfigDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  key?: StringWhereDto;
  description?: StringWhereDto;
}

export type SysConfigValue = { [key: string]: unknown };

export interface SysConfig {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  key: string;
  description: string;
  value: SysConfigValue;
  allowPermission: string[];
}

export type SysConfigDtoValue = { [key: string]: unknown };

export interface SysConfigDto {
  id: number;
  value: SysConfigDtoValue;
  description: string;
  allowPermission: string[];
}

export interface ItemTypeDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface ItemTypeDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  name?: StringWhereDto;
  description?: StringWhereDto;
  symbol?: StringWhereDto;
}

export interface LanguageDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface LanguageDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  code?: StringWhereDto;
  country?: StringWhereDto;
  value?: StringWhereDto;
}

export interface Language {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  code: string;
  country: string;
  value: string;
}

export interface LanguageDto {
  id?: number;
  code: string;
  country: string;
  value: string;
}

export interface LanguageCodeDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface LanguageCodeDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  code?: StringWhereDto;
  description?: StringWhereDto;
}

export interface LanguageCode {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  code: string;
  description: string;
}

export interface LanguageCodeDto {
  id?: number;
  code: string;
  description: string;
}

export interface LanguageCountryDtoFindManyOptions {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
}

export interface LanguageCountryDtoFindOptionsWhereDto {
  id?: NumberWhereDto;
  createdAt?: DateWhereDto;
  updatedAt?: DateWhereDto;
  deletedAt?: DateWhereDto;
  isLocked?: BooleanWhereDto;
  country?: StringWhereDto;
  description?: StringWhereDto;
}

export interface LanguageCountry {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  isLocked: boolean;
  country: string;
  description: string;
}

export interface LanguageCountryDto {
  id?: number;
  country: string;
  description: string;
}

export type EnumPermission =
  (typeof EnumPermission)[keyof typeof EnumPermission];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnumPermission = {
  AuthControllerMe: 'AuthController.Me',
  AuthController: 'AuthController',
  UserControllerView: 'UserController.View',
  UserControllerCreate: 'UserController.Create',
  UserControllerUpdate: 'UserController.Update',
  UserControllerDelete: 'UserController.Delete',
  UserControllerViewPermissions: 'UserController.ViewPermissions',
  UserControllerChangePermissions: 'UserController.ChangePermissions',
  UserControllerViewInventories: 'UserController.ViewInventories',
  UserControllerChangeInventories: 'UserController.ChangeInventories',
  UserControllerViewMyProfile: 'UserController.ViewMyProfile',
  UserController: 'UserController',
  PermissionControllerView: 'PermissionController.View',
  PermissionControllerCreate: 'PermissionController.Create',
  PermissionControllerUpdate: 'PermissionController.Update',
  PermissionControllerDelete: 'PermissionController.Delete',
  PermissionController: 'PermissionController',
  SysConfigControllerView: 'SysConfigController.View',
  SysConfigControllerCreate: 'SysConfigController.Create',
  SysConfigControllerUpdate: 'SysConfigController.Update',
  SysConfigController: 'SysConfigController',
  ItemTypeControllerView: 'ItemTypeController.View',
  ItemTypeControllerCreate: 'ItemTypeController.Create',
  ItemTypeControllerUpdate: 'ItemTypeController.Update',
  ItemTypeControllerDelete: 'ItemTypeController.Delete',
  ItemTypeController: 'ItemTypeController',
  LanguageControllerView: 'LanguageController.View',
  LanguageControllerCreate: 'LanguageController.Create',
  LanguageControllerUpdate: 'LanguageController.Update',
  LanguageControllerDelete: 'LanguageController.Delete',
  LanguageController: 'LanguageController',
  LanguageCodeControllerView: 'LanguageCodeController.View',
  LanguageCodeControllerCreate: 'LanguageCodeController.Create',
  LanguageCodeControllerUpdate: 'LanguageCodeController.Update',
  LanguageCodeControllerDelete: 'LanguageCodeController.Delete',
  LanguageCodeController: 'LanguageCodeController',
  LanguageCountryControllerView: 'LanguageCountryController.View',
  LanguageCountryControllerCreate: 'LanguageCountryController.Create',
  LanguageCountryControllerUpdate: 'LanguageCountryController.Update',
  LanguageCountryControllerDelete: 'LanguageCountryController.Delete',
  LanguageCountryController: 'LanguageCountryController',
} as const;

export interface RegistedPermissionDto {
  permission: EnumPermission;
}

export type PermissionControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: PermissionDtoFindOptionsWhereDto | PermissionDtoFindOptionsWhereDto[];
};

export type PermissionControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: PermissionDtoFindOptionsWhereDto | PermissionDtoFindOptionsWhereDto[];
};

export type UserControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: UserDtoFindOptionsWhereDto | UserDtoFindOptionsWhereDto[];
};

export type UserControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: UserDtoFindOptionsWhereDto | UserDtoFindOptionsWhereDto[];
};

export type AuthControllerMe200 = {
  email?: string;
  permissions?: string[];
};

export type SysConfigControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: SysConfigDtoFindOptionsWhereDto | SysConfigDtoFindOptionsWhereDto[];
};

export type SysConfigControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: SysConfigDtoFindOptionsWhereDto | SysConfigDtoFindOptionsWhereDto[];
};

export type ItemTypeControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: ItemTypeDtoFindOptionsWhereDto | ItemTypeDtoFindOptionsWhereDto[];
};

export type ItemTypeControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: ItemTypeDtoFindOptionsWhereDto | ItemTypeDtoFindOptionsWhereDto[];
};

export type LanguageControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: LanguageDtoFindOptionsWhereDto | LanguageDtoFindOptionsWhereDto[];
};

export type LanguageControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?: LanguageDtoFindOptionsWhereDto | LanguageDtoFindOptionsWhereDto[];
};

export type LanguageCodeControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?:
    | LanguageCodeDtoFindOptionsWhereDto
    | LanguageCodeDtoFindOptionsWhereDto[];
};

export type LanguageCodeControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?:
    | LanguageCodeDtoFindOptionsWhereDto
    | LanguageCodeDtoFindOptionsWhereDto[];
};

export type LanguageCountryControllerCountParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?:
    | LanguageCountryDtoFindOptionsWhereDto
    | LanguageCountryDtoFindOptionsWhereDto[];
};

export type LanguageCountryControllerFindAllParams = {
  skip?: number;
  take?: number;
  withDeleted?: boolean;
  where?:
    | LanguageCountryDtoFindOptionsWhereDto
    | LanguageCountryDtoFindOptionsWhereDto[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const permissionControllerFindAllWithRelations = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PermissionRelationsDto[]>(
    { url: `/api/permissions/findAllWithRelations`, method: 'GET' },
    options,
  );
};

export const getPermissionControllerFindAllWithRelationsKey = () =>
  [`/api/permissions/findAllWithRelations`] as const;

export type PermissionControllerFindAllWithRelationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerFindAllWithRelations>>
>;
export type PermissionControllerFindAllWithRelationsQueryError = unknown;

export const usePermissionControllerFindAllWithRelations = <
  TError = unknown,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof permissionControllerFindAllWithRelations>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() =>
      isEnabled ? getPermissionControllerFindAllWithRelationsKey() : null);
  const swrFn = () => permissionControllerFindAllWithRelations(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerUpdateRelations = (
  permissionRelationsDto: PermissionRelationsDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/permissions/updateRelations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: permissionRelationsDto,
    },
    options,
  );
};

export const getPermissionControllerUpdateRelationsMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: PermissionRelationsDto }): Promise<null> => {
    return permissionControllerUpdateRelations(arg, options);
  };
};
export const getPermissionControllerUpdateRelationsMutationKey = () =>
  [`/api/permissions/updateRelations`] as const;

export type PermissionControllerUpdateRelationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerUpdateRelations>>
>;
export type PermissionControllerUpdateRelationsMutationError = unknown;

export const usePermissionControllerUpdateRelations = <
  TError = unknown,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof permissionControllerUpdateRelations>>,
    TError,
    Key,
    PermissionRelationsDto,
    Awaited<ReturnType<typeof permissionControllerUpdateRelations>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPermissionControllerUpdateRelationsMutationKey();
  const swrFn =
    getPermissionControllerUpdateRelationsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerCount = (
  params?: PermissionControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/permissions/count`, method: 'GET', params },
    options,
  );
};

export const getPermissionControllerCountKey = (
  params?: PermissionControllerCountParams,
) => [`/api/permissions/count`, ...(params ? [params] : [])] as const;

export type PermissionControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerCount>>
>;
export type PermissionControllerCountQueryError = unknown;

export const usePermissionControllerCount = <TError = unknown>(
  params?: PermissionControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof permissionControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getPermissionControllerCountKey(params) : null));
  const swrFn = () => permissionControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerFindAll = (
  params?: PermissionControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Permission[]>(
    { url: `/api/permissions`, method: 'GET', params },
    options,
  );
};

export const getPermissionControllerFindAllKey = (
  params?: PermissionControllerFindAllParams,
) => [`/api/permissions`, ...(params ? [params] : [])] as const;

export type PermissionControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerFindAll>>
>;
export type PermissionControllerFindAllQueryError = unknown;

export const usePermissionControllerFindAll = <TError = unknown>(
  params?: PermissionControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof permissionControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getPermissionControllerFindAllKey(params) : null));
  const swrFn = () => permissionControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerCreate = (
  permissionDto: PermissionDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/permissions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: permissionDto,
    },
    options,
  );
};

export const getPermissionControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: PermissionDto }): Promise<null> => {
    return permissionControllerCreate(arg, options);
  };
};
export const getPermissionControllerCreateMutationKey = () =>
  [`/api/permissions`] as const;

export type PermissionControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerCreate>>
>;
export type PermissionControllerCreateMutationError = unknown;

export const usePermissionControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof permissionControllerCreate>>,
    TError,
    Key,
    PermissionDto,
    Awaited<ReturnType<typeof permissionControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPermissionControllerCreateMutationKey();
  const swrFn = getPermissionControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Permission>(
    { url: `/api/permissions/${id}`, method: 'GET' },
    options,
  );
};

export const getPermissionControllerFindByIdKey = (id: number) =>
  [`/api/permissions/${id}`] as const;

export type PermissionControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerFindById>>
>;
export type PermissionControllerFindByIdQueryError = unknown;

export const usePermissionControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof permissionControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getPermissionControllerFindByIdKey(id) : null));
  const swrFn = () => permissionControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerUpdate = (
  id: number,
  permissionDto: PermissionDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/permissions/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: permissionDto,
    },
    options,
  );
};

export const getPermissionControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: PermissionDto }): Promise<null> => {
    return permissionControllerUpdate(id, arg, options);
  };
};
export const getPermissionControllerUpdateMutationKey = (id: number) =>
  [`/api/permissions/${id}`] as const;

export type PermissionControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerUpdate>>
>;
export type PermissionControllerUpdateMutationError = unknown;

export const usePermissionControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof permissionControllerUpdate>>,
      TError,
      Key,
      PermissionDto,
      Awaited<ReturnType<typeof permissionControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPermissionControllerUpdateMutationKey(id);
  const swrFn = getPermissionControllerUpdateMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const permissionControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/permissions/${id}`, method: 'DELETE' },
    options,
  );
};

export const getPermissionControllerDeleteMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<null> => {
    return permissionControllerDelete(id, options);
  };
};
export const getPermissionControllerDeleteMutationKey = (id: number) =>
  [`/api/permissions/${id}`] as const;

export type PermissionControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof permissionControllerDelete>>
>;
export type PermissionControllerDeleteMutationError = unknown;

export const usePermissionControllerDelete = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof permissionControllerDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof permissionControllerDelete>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getPermissionControllerDeleteMutationKey(id);
  const swrFn = getPermissionControllerDeleteMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const userControllerFindOneWithPermissions = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User>(
    { url: `/api/users/findOneWithPermissions/${id}`, method: 'GET' },
    options,
  );
};

export const getUserControllerFindOneWithPermissionsKey = (id: number) =>
  [`/api/users/findOneWithPermissions/${id}`] as const;

export type UserControllerFindOneWithPermissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindOneWithPermissions>>
>;
export type UserControllerFindOneWithPermissionsQueryError = unknown;

export const useUserControllerFindOneWithPermissions = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof userControllerFindOneWithPermissions>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getUserControllerFindOneWithPermissionsKey(id) : null));
  const swrFn = () => userControllerFindOneWithPermissions(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const userControllerUpdateWithPermissions = (
  id: number,
  userPermissionDto: UserPermissionDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/users/updateWithPermissions/${id}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userPermissionDto,
    },
    options,
  );
};

export const getUserControllerUpdateWithPermissionsMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: UserPermissionDto }): Promise<null> => {
    return userControllerUpdateWithPermissions(id, arg, options);
  };
};
export const getUserControllerUpdateWithPermissionsMutationKey = (id: number) =>
  [`/api/users/updateWithPermissions/${id}`] as const;

export type UserControllerUpdateWithPermissionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateWithPermissions>>
>;
export type UserControllerUpdateWithPermissionsMutationError = unknown;

export const useUserControllerUpdateWithPermissions = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userControllerUpdateWithPermissions>>,
      TError,
      Key,
      UserPermissionDto,
      Awaited<ReturnType<typeof userControllerUpdateWithPermissions>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getUserControllerUpdateWithPermissionsMutationKey(id);
  const swrFn = getUserControllerUpdateWithPermissionsMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const userControllerFindOneWithInventories = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User>(
    { url: `/api/users/findOneWithInventories/${id}`, method: 'GET' },
    options,
  );
};

export const getUserControllerFindOneWithInventoriesKey = (id: number) =>
  [`/api/users/findOneWithInventories/${id}`] as const;

export type UserControllerFindOneWithInventoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindOneWithInventories>>
>;
export type UserControllerFindOneWithInventoriesQueryError = unknown;

export const useUserControllerFindOneWithInventories = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof userControllerFindOneWithInventories>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getUserControllerFindOneWithInventoriesKey(id) : null));
  const swrFn = () => userControllerFindOneWithInventories(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const userControllerUpdateWithInventories = (
  id: number,
  userInventoriesDto: UserInventoriesDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/users/updateWithInventories/${id}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userInventoriesDto,
    },
    options,
  );
};

export const getUserControllerUpdateWithInventoriesMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: UserInventoriesDto }): Promise<null> => {
    return userControllerUpdateWithInventories(id, arg, options);
  };
};
export const getUserControllerUpdateWithInventoriesMutationKey = (id: number) =>
  [`/api/users/updateWithInventories/${id}`] as const;

export type UserControllerUpdateWithInventoriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateWithInventories>>
>;
export type UserControllerUpdateWithInventoriesMutationError = unknown;

export const useUserControllerUpdateWithInventories = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userControllerUpdateWithInventories>>,
      TError,
      Key,
      UserInventoriesDto,
      Awaited<ReturnType<typeof userControllerUpdateWithInventories>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getUserControllerUpdateWithInventoriesMutationKey(id);
  const swrFn = getUserControllerUpdateWithInventoriesMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const userControllerGetMyProfile = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User>(
    { url: `/api/users/getMyProfile`, method: 'GET' },
    options,
  );
};

export const getUserControllerGetMyProfileKey = () =>
  [`/api/users/getMyProfile`] as const;

export type UserControllerGetMyProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetMyProfile>>
>;
export type UserControllerGetMyProfileQueryError = unknown;

export const useUserControllerGetMyProfile = <TError = unknown>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof userControllerGetMyProfile>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getUserControllerGetMyProfileKey() : null));
  const swrFn = () => userControllerGetMyProfile(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const userControllerUpdateWithInventoriesTracking = (
  id: number,
  userInventoriesTrackingDto: UserInventoriesTrackingDto[],
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/users/updateWithInventoriesTracking/${id}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userInventoriesTrackingDto,
    },
    options,
  );
};

export const getUserControllerUpdateWithInventoriesTrackingMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: UserInventoriesTrackingDto[] },
  ): Promise<null> => {
    return userControllerUpdateWithInventoriesTracking(id, arg, options);
  };
};
export const getUserControllerUpdateWithInventoriesTrackingMutationKey = (
  id: number,
) => [`/api/users/updateWithInventoriesTracking/${id}`] as const;

export type UserControllerUpdateWithInventoriesTrackingMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof userControllerUpdateWithInventoriesTracking>>
  >;
export type UserControllerUpdateWithInventoriesTrackingMutationError = unknown;

export const useUserControllerUpdateWithInventoriesTracking = <
  TError = unknown,
>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userControllerUpdateWithInventoriesTracking>>,
      TError,
      Key,
      UserInventoriesTrackingDto[],
      Awaited<ReturnType<typeof userControllerUpdateWithInventoriesTracking>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ??
    getUserControllerUpdateWithInventoriesTrackingMutationKey(id);
  const swrFn = getUserControllerUpdateWithInventoriesTrackingMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const userControllerCount = (
  params?: UserControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/users/count`, method: 'GET', params },
    options,
  );
};

export const getUserControllerCountKey = (params?: UserControllerCountParams) =>
  [`/api/users/count`, ...(params ? [params] : [])] as const;

export type UserControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerCount>>
>;
export type UserControllerCountQueryError = unknown;

export const useUserControllerCount = <TError = unknown>(
  params?: UserControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof userControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getUserControllerCountKey(params) : null));
  const swrFn = () => userControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const userControllerFindAll = (
  params?: UserControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User[]>(
    { url: `/api/users`, method: 'GET', params },
    options,
  );
};

export const getUserControllerFindAllKey = (
  params?: UserControllerFindAllParams,
) => [`/api/users`, ...(params ? [params] : [])] as const;

export type UserControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindAll>>
>;
export type UserControllerFindAllQueryError = unknown;

export const useUserControllerFindAll = <TError = unknown>(
  params?: UserControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof userControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getUserControllerFindAllKey(params) : null));
  const swrFn = () => userControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const userControllerCreate = (
  userDto: UserDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/users`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userDto,
    },
    options,
  );
};

export const getUserControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: UserDto }): Promise<null> => {
    return userControllerCreate(arg, options);
  };
};
export const getUserControllerCreateMutationKey = () => [`/api/users`] as const;

export type UserControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerCreate>>
>;
export type UserControllerCreateMutationError = unknown;

export const useUserControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof userControllerCreate>>,
    TError,
    Key,
    UserDto,
    Awaited<ReturnType<typeof userControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUserControllerCreateMutationKey();
  const swrFn = getUserControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const userControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User>(
    { url: `/api/users/${id}`, method: 'GET' },
    options,
  );
};

export const getUserControllerFindByIdKey = (id: number) =>
  [`/api/users/${id}`] as const;

export type UserControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindById>>
>;
export type UserControllerFindByIdQueryError = unknown;

export const useUserControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof userControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getUserControllerFindByIdKey(id) : null));
  const swrFn = () => userControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const userControllerUpdate = (
  id: number,
  userDto: UserDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/users/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: userDto,
    },
    options,
  );
};

export const getUserControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: UserDto }): Promise<null> => {
    return userControllerUpdate(id, arg, options);
  };
};
export const getUserControllerUpdateMutationKey = (id: number) =>
  [`/api/users/${id}`] as const;

export type UserControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdate>>
>;
export type UserControllerUpdateMutationError = unknown;

export const useUserControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userControllerUpdate>>,
      TError,
      Key,
      UserDto,
      Awaited<ReturnType<typeof userControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUserControllerUpdateMutationKey(id);
  const swrFn = getUserControllerUpdateMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const userControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/users/${id}`, method: 'DELETE' },
    options,
  );
};

export const getUserControllerDeleteMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<null> => {
    return userControllerDelete(id, options);
  };
};
export const getUserControllerDeleteMutationKey = (id: number) =>
  [`/api/users/${id}`] as const;

export type UserControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerDelete>>
>;
export type UserControllerDeleteMutationError = unknown;

export const useUserControllerDelete = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userControllerDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof userControllerDelete>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUserControllerDeleteMutationKey(id);
  const swrFn = getUserControllerDeleteMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const authControllerGoogleAuth = (
  googleAuthDto: GoogleAuthDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GoogleAuthResponseDto>(
    {
      url: `/api/auth/google`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: googleAuthDto,
    },
    options,
  );
};

export const getAuthControllerGoogleAuthMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: GoogleAuthDto },
  ): Promise<GoogleAuthResponseDto> => {
    return authControllerGoogleAuth(arg, options);
  };
};
export const getAuthControllerGoogleAuthMutationKey = () =>
  [`/api/auth/google`] as const;

export type AuthControllerGoogleAuthMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleAuth>>
>;
export type AuthControllerGoogleAuthMutationError = unknown;

export const useAuthControllerGoogleAuth = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authControllerGoogleAuth>>,
    TError,
    Key,
    GoogleAuthDto,
    Awaited<ReturnType<typeof authControllerGoogleAuth>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthControllerGoogleAuthMutationKey();
  const swrFn = getAuthControllerGoogleAuthMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const authControllerConfig = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetConfigDto>(
    { url: `/api/auth/config`, method: 'GET' },
    options,
  );
};

export const getAuthControllerConfigKey = () => [`/api/auth/config`] as const;

export type AuthControllerConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerConfig>>
>;
export type AuthControllerConfigQueryError = unknown;

export const useAuthControllerConfig = <TError = unknown>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof authControllerConfig>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getAuthControllerConfigKey() : null));
  const swrFn = () => authControllerConfig(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const authControllerMe = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuthControllerMe200>(
    { url: `/api/auth/me`, method: 'GET' },
    options,
  );
};

export const getAuthControllerMeKey = () => [`/api/auth/me`] as const;

export type AuthControllerMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerMe>>
>;
export type AuthControllerMeQueryError = unknown;

export const useAuthControllerMe = <TError = unknown>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof authControllerMe>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAuthControllerMeKey() : null));
  const swrFn = () => authControllerMe(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const sysConfigControllerCount = (
  params?: SysConfigControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/sys-config/count`, method: 'GET', params },
    options,
  );
};

export const getSysConfigControllerCountKey = (
  params?: SysConfigControllerCountParams,
) => [`/api/sys-config/count`, ...(params ? [params] : [])] as const;

export type SysConfigControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof sysConfigControllerCount>>
>;
export type SysConfigControllerCountQueryError = unknown;

export const useSysConfigControllerCount = <TError = unknown>(
  params?: SysConfigControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof sysConfigControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getSysConfigControllerCountKey(params) : null));
  const swrFn = () => sysConfigControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const sysConfigControllerFindAll = (
  params?: SysConfigControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SysConfig[]>(
    { url: `/api/sys-config`, method: 'GET', params },
    options,
  );
};

export const getSysConfigControllerFindAllKey = (
  params?: SysConfigControllerFindAllParams,
) => [`/api/sys-config`, ...(params ? [params] : [])] as const;

export type SysConfigControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof sysConfigControllerFindAll>>
>;
export type SysConfigControllerFindAllQueryError = unknown;

export const useSysConfigControllerFindAll = <TError = unknown>(
  params?: SysConfigControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof sysConfigControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getSysConfigControllerFindAllKey(params) : null));
  const swrFn = () => sysConfigControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const sysConfigControllerCreate = (
  sysConfigDto: SysConfigDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/sys-config`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sysConfigDto,
    },
    options,
  );
};

export const getSysConfigControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: SysConfigDto }): Promise<null> => {
    return sysConfigControllerCreate(arg, options);
  };
};
export const getSysConfigControllerCreateMutationKey = () =>
  [`/api/sys-config`] as const;

export type SysConfigControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof sysConfigControllerCreate>>
>;
export type SysConfigControllerCreateMutationError = unknown;

export const useSysConfigControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof sysConfigControllerCreate>>,
    TError,
    Key,
    SysConfigDto,
    Awaited<ReturnType<typeof sysConfigControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getSysConfigControllerCreateMutationKey();
  const swrFn = getSysConfigControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const sysConfigControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SysConfig>(
    { url: `/api/sys-config/${id}`, method: 'GET' },
    options,
  );
};

export const getSysConfigControllerFindByIdKey = (id: number) =>
  [`/api/sys-config/${id}`] as const;

export type SysConfigControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof sysConfigControllerFindById>>
>;
export type SysConfigControllerFindByIdQueryError = unknown;

export const useSysConfigControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof sysConfigControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getSysConfigControllerFindByIdKey(id) : null));
  const swrFn = () => sysConfigControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const sysConfigControllerUpdate = (
  id: number,
  sysConfigDto: SysConfigDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/sys-config/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: sysConfigDto,
    },
    options,
  );
};

export const getSysConfigControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: SysConfigDto }): Promise<null> => {
    return sysConfigControllerUpdate(id, arg, options);
  };
};
export const getSysConfigControllerUpdateMutationKey = (id: number) =>
  [`/api/sys-config/${id}`] as const;

export type SysConfigControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof sysConfigControllerUpdate>>
>;
export type SysConfigControllerUpdateMutationError = unknown;

export const useSysConfigControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof sysConfigControllerUpdate>>,
      TError,
      Key,
      SysConfigDto,
      Awaited<ReturnType<typeof sysConfigControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getSysConfigControllerUpdateMutationKey(id);
  const swrFn = getSysConfigControllerUpdateMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const itemTypeControllerCount = (
  params?: ItemTypeControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/item-type/count`, method: 'GET', params },
    options,
  );
};

export const getItemTypeControllerCountKey = (
  params?: ItemTypeControllerCountParams,
) => [`/api/item-type/count`, ...(params ? [params] : [])] as const;

export type ItemTypeControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof itemTypeControllerCount>>
>;
export type ItemTypeControllerCountQueryError = unknown;

export const useItemTypeControllerCount = <TError = unknown>(
  params?: ItemTypeControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof itemTypeControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getItemTypeControllerCountKey(params) : null));
  const swrFn = () => itemTypeControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const itemTypeControllerFindAll = (
  params?: ItemTypeControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ItemType[]>(
    { url: `/api/item-type`, method: 'GET', params },
    options,
  );
};

export const getItemTypeControllerFindAllKey = (
  params?: ItemTypeControllerFindAllParams,
) => [`/api/item-type`, ...(params ? [params] : [])] as const;

export type ItemTypeControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof itemTypeControllerFindAll>>
>;
export type ItemTypeControllerFindAllQueryError = unknown;

export const useItemTypeControllerFindAll = <TError = unknown>(
  params?: ItemTypeControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof itemTypeControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getItemTypeControllerFindAllKey(params) : null));
  const swrFn = () => itemTypeControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const itemTypeControllerCreate = (
  itemTypeDto: ItemTypeDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/item-type`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: itemTypeDto,
    },
    options,
  );
};

export const getItemTypeControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: ItemTypeDto }): Promise<null> => {
    return itemTypeControllerCreate(arg, options);
  };
};
export const getItemTypeControllerCreateMutationKey = () =>
  [`/api/item-type`] as const;

export type ItemTypeControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof itemTypeControllerCreate>>
>;
export type ItemTypeControllerCreateMutationError = unknown;

export const useItemTypeControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof itemTypeControllerCreate>>,
    TError,
    Key,
    ItemTypeDto,
    Awaited<ReturnType<typeof itemTypeControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getItemTypeControllerCreateMutationKey();
  const swrFn = getItemTypeControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const itemTypeControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ItemType>(
    { url: `/api/item-type/${id}`, method: 'GET' },
    options,
  );
};

export const getItemTypeControllerFindByIdKey = (id: number) =>
  [`/api/item-type/${id}`] as const;

export type ItemTypeControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof itemTypeControllerFindById>>
>;
export type ItemTypeControllerFindByIdQueryError = unknown;

export const useItemTypeControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof itemTypeControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getItemTypeControllerFindByIdKey(id) : null));
  const swrFn = () => itemTypeControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const itemTypeControllerUpdate = (
  id: number,
  itemTypeDto: ItemTypeDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/item-type/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: itemTypeDto,
    },
    options,
  );
};

export const getItemTypeControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: ItemTypeDto }): Promise<null> => {
    return itemTypeControllerUpdate(id, arg, options);
  };
};
export const getItemTypeControllerUpdateMutationKey = (id: number) =>
  [`/api/item-type/${id}`] as const;

export type ItemTypeControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof itemTypeControllerUpdate>>
>;
export type ItemTypeControllerUpdateMutationError = unknown;

export const useItemTypeControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof itemTypeControllerUpdate>>,
      TError,
      Key,
      ItemTypeDto,
      Awaited<ReturnType<typeof itemTypeControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getItemTypeControllerUpdateMutationKey(id);
  const swrFn = getItemTypeControllerUpdateMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const itemTypeControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/item-type/${id}`, method: 'DELETE' },
    options,
  );
};

export const getItemTypeControllerDeleteMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<null> => {
    return itemTypeControllerDelete(id, options);
  };
};
export const getItemTypeControllerDeleteMutationKey = (id: number) =>
  [`/api/item-type/${id}`] as const;

export type ItemTypeControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof itemTypeControllerDelete>>
>;
export type ItemTypeControllerDeleteMutationError = unknown;

export const useItemTypeControllerDelete = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof itemTypeControllerDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof itemTypeControllerDelete>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getItemTypeControllerDeleteMutationKey(id);
  const swrFn = getItemTypeControllerDeleteMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageControllerCount = (
  params?: LanguageControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/languages/count`, method: 'GET', params },
    options,
  );
};

export const getLanguageControllerCountKey = (
  params?: LanguageControllerCountParams,
) => [`/api/languages/count`, ...(params ? [params] : [])] as const;

export type LanguageControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageControllerCount>>
>;
export type LanguageControllerCountQueryError = unknown;

export const useLanguageControllerCount = <TError = unknown>(
  params?: LanguageControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageControllerCountKey(params) : null));
  const swrFn = () => languageControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageControllerFindAll = (
  params?: LanguageControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Language[]>(
    { url: `/api/languages`, method: 'GET', params },
    options,
  );
};

export const getLanguageControllerFindAllKey = (
  params?: LanguageControllerFindAllParams,
) => [`/api/languages`, ...(params ? [params] : [])] as const;

export type LanguageControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageControllerFindAll>>
>;
export type LanguageControllerFindAllQueryError = unknown;

export const useLanguageControllerFindAll = <TError = unknown>(
  params?: LanguageControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageControllerFindAllKey(params) : null));
  const swrFn = () => languageControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageControllerCreate = (
  languageDto: LanguageDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/languages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: languageDto,
    },
    options,
  );
};

export const getLanguageControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: LanguageDto }): Promise<null> => {
    return languageControllerCreate(arg, options);
  };
};
export const getLanguageControllerCreateMutationKey = () =>
  [`/api/languages`] as const;

export type LanguageControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageControllerCreate>>
>;
export type LanguageControllerCreateMutationError = unknown;

export const useLanguageControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof languageControllerCreate>>,
    TError,
    Key,
    LanguageDto,
    Awaited<ReturnType<typeof languageControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getLanguageControllerCreateMutationKey();
  const swrFn = getLanguageControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Language>(
    { url: `/api/languages/${id}`, method: 'GET' },
    options,
  );
};

export const getLanguageControllerFindByIdKey = (id: number) =>
  [`/api/languages/${id}`] as const;

export type LanguageControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageControllerFindById>>
>;
export type LanguageControllerFindByIdQueryError = unknown;

export const useLanguageControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageControllerFindByIdKey(id) : null));
  const swrFn = () => languageControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageControllerUpdate = (
  id: number,
  languageDto: LanguageDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/languages/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: languageDto,
    },
    options,
  );
};

export const getLanguageControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: LanguageDto }): Promise<null> => {
    return languageControllerUpdate(id, arg, options);
  };
};
export const getLanguageControllerUpdateMutationKey = (id: number) =>
  [`/api/languages/${id}`] as const;

export type LanguageControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageControllerUpdate>>
>;
export type LanguageControllerUpdateMutationError = unknown;

export const useLanguageControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof languageControllerUpdate>>,
      TError,
      Key,
      LanguageDto,
      Awaited<ReturnType<typeof languageControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageControllerUpdateMutationKey(id);
  const swrFn = getLanguageControllerUpdateMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/languages/${id}`, method: 'DELETE' },
    options,
  );
};

export const getLanguageControllerDeleteMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<null> => {
    return languageControllerDelete(id, options);
  };
};
export const getLanguageControllerDeleteMutationKey = (id: number) =>
  [`/api/languages/${id}`] as const;

export type LanguageControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageControllerDelete>>
>;
export type LanguageControllerDeleteMutationError = unknown;

export const useLanguageControllerDelete = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof languageControllerDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof languageControllerDelete>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageControllerDeleteMutationKey(id);
  const swrFn = getLanguageControllerDeleteMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languagePublicControllerGetCountries = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/language-public/countries`, method: 'GET' },
    options,
  );
};

export const getLanguagePublicControllerGetCountriesKey = () =>
  [`/api/language-public/countries`] as const;

export type LanguagePublicControllerGetCountriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof languagePublicControllerGetCountries>>
>;
export type LanguagePublicControllerGetCountriesQueryError = unknown;

export const useLanguagePublicControllerGetCountries = <
  TError = unknown,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof languagePublicControllerGetCountries>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguagePublicControllerGetCountriesKey() : null));
  const swrFn = () => languagePublicControllerGetCountries(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languagePublicControllerGetCodes = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/language-public/codes`, method: 'GET' },
    options,
  );
};

export const getLanguagePublicControllerGetCodesKey = () =>
  [`/api/language-public/codes`] as const;

export type LanguagePublicControllerGetCodesQueryResult = NonNullable<
  Awaited<ReturnType<typeof languagePublicControllerGetCodes>>
>;
export type LanguagePublicControllerGetCodesQueryError = unknown;

export const useLanguagePublicControllerGetCodes = <
  TError = unknown,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof languagePublicControllerGetCodes>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguagePublicControllerGetCodesKey() : null));
  const swrFn = () => languagePublicControllerGetCodes(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languagePublicControllerGetLanguages = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/language-public/languages`, method: 'GET' },
    options,
  );
};

export const getLanguagePublicControllerGetLanguagesKey = () =>
  [`/api/language-public/languages`] as const;

export type LanguagePublicControllerGetLanguagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof languagePublicControllerGetLanguages>>
>;
export type LanguagePublicControllerGetLanguagesQueryError = unknown;

export const useLanguagePublicControllerGetLanguages = <
  TError = unknown,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof languagePublicControllerGetLanguages>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguagePublicControllerGetLanguagesKey() : null));
  const swrFn = () => languagePublicControllerGetLanguages(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languagePublicControllerGet = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/language-public`, method: 'GET' },
    options,
  );
};

export const getLanguagePublicControllerGetKey = () =>
  [`/api/language-public`] as const;

export type LanguagePublicControllerGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof languagePublicControllerGet>>
>;
export type LanguagePublicControllerGetQueryError = unknown;

export const useLanguagePublicControllerGet = <TError = unknown>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof languagePublicControllerGet>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguagePublicControllerGetKey() : null));
  const swrFn = () => languagePublicControllerGet(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCodeControllerCount = (
  params?: LanguageCodeControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/language-codes/count`, method: 'GET', params },
    options,
  );
};

export const getLanguageCodeControllerCountKey = (
  params?: LanguageCodeControllerCountParams,
) => [`/api/language-codes/count`, ...(params ? [params] : [])] as const;

export type LanguageCodeControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageCodeControllerCount>>
>;
export type LanguageCodeControllerCountQueryError = unknown;

export const useLanguageCodeControllerCount = <TError = unknown>(
  params?: LanguageCodeControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageCodeControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageCodeControllerCountKey(params) : null));
  const swrFn = () => languageCodeControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCodeControllerFindAll = (
  params?: LanguageCodeControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<LanguageCode[]>(
    { url: `/api/language-codes`, method: 'GET', params },
    options,
  );
};

export const getLanguageCodeControllerFindAllKey = (
  params?: LanguageCodeControllerFindAllParams,
) => [`/api/language-codes`, ...(params ? [params] : [])] as const;

export type LanguageCodeControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageCodeControllerFindAll>>
>;
export type LanguageCodeControllerFindAllQueryError = unknown;

export const useLanguageCodeControllerFindAll = <TError = unknown>(
  params?: LanguageCodeControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageCodeControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageCodeControllerFindAllKey(params) : null));
  const swrFn = () => languageCodeControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCodeControllerCreate = (
  languageCodeDto: LanguageCodeDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/language-codes`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: languageCodeDto,
    },
    options,
  );
};

export const getLanguageCodeControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: LanguageCodeDto }): Promise<null> => {
    return languageCodeControllerCreate(arg, options);
  };
};
export const getLanguageCodeControllerCreateMutationKey = () =>
  [`/api/language-codes`] as const;

export type LanguageCodeControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageCodeControllerCreate>>
>;
export type LanguageCodeControllerCreateMutationError = unknown;

export const useLanguageCodeControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof languageCodeControllerCreate>>,
    TError,
    Key,
    LanguageCodeDto,
    Awaited<ReturnType<typeof languageCodeControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageCodeControllerCreateMutationKey();
  const swrFn = getLanguageCodeControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageCodeControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<LanguageCode>(
    { url: `/api/language-codes/${id}`, method: 'GET' },
    options,
  );
};

export const getLanguageCodeControllerFindByIdKey = (id: number) =>
  [`/api/language-codes/${id}`] as const;

export type LanguageCodeControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageCodeControllerFindById>>
>;
export type LanguageCodeControllerFindByIdQueryError = unknown;

export const useLanguageCodeControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageCodeControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageCodeControllerFindByIdKey(id) : null));
  const swrFn = () => languageCodeControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCodeControllerUpdate = (
  id: number,
  languageCodeDto: LanguageCodeDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/language-codes/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: languageCodeDto,
    },
    options,
  );
};

export const getLanguageCodeControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: LanguageCodeDto }): Promise<null> => {
    return languageCodeControllerUpdate(id, arg, options);
  };
};
export const getLanguageCodeControllerUpdateMutationKey = (id: number) =>
  [`/api/language-codes/${id}`] as const;

export type LanguageCodeControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageCodeControllerUpdate>>
>;
export type LanguageCodeControllerUpdateMutationError = unknown;

export const useLanguageCodeControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof languageCodeControllerUpdate>>,
      TError,
      Key,
      LanguageCodeDto,
      Awaited<ReturnType<typeof languageCodeControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageCodeControllerUpdateMutationKey(id);
  const swrFn = getLanguageCodeControllerUpdateMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageCodeControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/language-codes/${id}`, method: 'DELETE' },
    options,
  );
};

export const getLanguageCodeControllerDeleteMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<null> => {
    return languageCodeControllerDelete(id, options);
  };
};
export const getLanguageCodeControllerDeleteMutationKey = (id: number) =>
  [`/api/language-codes/${id}`] as const;

export type LanguageCodeControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageCodeControllerDelete>>
>;
export type LanguageCodeControllerDeleteMutationError = unknown;

export const useLanguageCodeControllerDelete = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof languageCodeControllerDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof languageCodeControllerDelete>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageCodeControllerDeleteMutationKey(id);
  const swrFn = getLanguageCodeControllerDeleteMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageCountryControllerCount = (
  params?: LanguageCountryControllerCountParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<number>(
    { url: `/api/language-countries/count`, method: 'GET', params },
    options,
  );
};

export const getLanguageCountryControllerCountKey = (
  params?: LanguageCountryControllerCountParams,
) => [`/api/language-countries/count`, ...(params ? [params] : [])] as const;

export type LanguageCountryControllerCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageCountryControllerCount>>
>;
export type LanguageCountryControllerCountQueryError = unknown;

export const useLanguageCountryControllerCount = <TError = unknown>(
  params?: LanguageCountryControllerCountParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageCountryControllerCount>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageCountryControllerCountKey(params) : null));
  const swrFn = () => languageCountryControllerCount(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCountryControllerFindAll = (
  params?: LanguageCountryControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<LanguageCountry[]>(
    { url: `/api/language-countries`, method: 'GET', params },
    options,
  );
};

export const getLanguageCountryControllerFindAllKey = (
  params?: LanguageCountryControllerFindAllParams,
) => [`/api/language-countries`, ...(params ? [params] : [])] as const;

export type LanguageCountryControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageCountryControllerFindAll>>
>;
export type LanguageCountryControllerFindAllQueryError = unknown;

export const useLanguageCountryControllerFindAll = <TError = unknown>(
  params?: LanguageCountryControllerFindAllParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageCountryControllerFindAll>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageCountryControllerFindAllKey(params) : null));
  const swrFn = () => languageCountryControllerFindAll(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCountryControllerCreate = (
  languageCountryDto: LanguageCountryDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/language-countries`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: languageCountryDto,
    },
    options,
  );
};

export const getLanguageCountryControllerCreateMutationFetcher = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: LanguageCountryDto }): Promise<null> => {
    return languageCountryControllerCreate(arg, options);
  };
};
export const getLanguageCountryControllerCreateMutationKey = () =>
  [`/api/language-countries`] as const;

export type LanguageCountryControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageCountryControllerCreate>>
>;
export type LanguageCountryControllerCreateMutationError = unknown;

export const useLanguageCountryControllerCreate = <TError = unknown>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof languageCountryControllerCreate>>,
    TError,
    Key,
    LanguageCountryDto,
    Awaited<ReturnType<typeof languageCountryControllerCreate>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageCountryControllerCreateMutationKey();
  const swrFn =
    getLanguageCountryControllerCreateMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageCountryControllerFindById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<LanguageCountry>(
    { url: `/api/language-countries/${id}`, method: 'GET' },
    options,
  );
};

export const getLanguageCountryControllerFindByIdKey = (id: number) =>
  [`/api/language-countries/${id}`] as const;

export type LanguageCountryControllerFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof languageCountryControllerFindById>>
>;
export type LanguageCountryControllerFindByIdQueryError = unknown;

export const useLanguageCountryControllerFindById = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof languageCountryControllerFindById>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLanguageCountryControllerFindByIdKey(id) : null));
  const swrFn = () => languageCountryControllerFindById(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

export const languageCountryControllerUpdate = (
  id: number,
  languageCountryDto: LanguageCountryDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    {
      url: `/api/language-countries/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: languageCountryDto,
    },
    options,
  );
};

export const getLanguageCountryControllerUpdateMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, { arg }: { arg: LanguageCountryDto }): Promise<null> => {
    return languageCountryControllerUpdate(id, arg, options);
  };
};
export const getLanguageCountryControllerUpdateMutationKey = (id: number) =>
  [`/api/language-countries/${id}`] as const;

export type LanguageCountryControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageCountryControllerUpdate>>
>;
export type LanguageCountryControllerUpdateMutationError = unknown;

export const useLanguageCountryControllerUpdate = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof languageCountryControllerUpdate>>,
      TError,
      Key,
      LanguageCountryDto,
      Awaited<ReturnType<typeof languageCountryControllerUpdate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageCountryControllerUpdateMutationKey(id);
  const swrFn = getLanguageCountryControllerUpdateMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const languageCountryControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<null>(
    { url: `/api/language-countries/${id}`, method: 'DELETE' },
    options,
  );
};

export const getLanguageCountryControllerDeleteMutationFetcher = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<null> => {
    return languageCountryControllerDelete(id, options);
  };
};
export const getLanguageCountryControllerDeleteMutationKey = (id: number) =>
  [`/api/language-countries/${id}`] as const;

export type LanguageCountryControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof languageCountryControllerDelete>>
>;
export type LanguageCountryControllerDeleteMutationError = unknown;

export const useLanguageCountryControllerDelete = <TError = unknown>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof languageCountryControllerDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof languageCountryControllerDelete>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getLanguageCountryControllerDeleteMutationKey(id);
  const swrFn = getLanguageCountryControllerDeleteMutationFetcher(
    id,
    requestOptions,
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const exportPermissionControllerAllPermissions = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<RegistedPermissionDto[]>(
    { url: `/api/export-permission/allPermissions`, method: 'GET' },
    options,
  );
};

export const getExportPermissionControllerAllPermissionsKey = () =>
  [`/api/export-permission/allPermissions`] as const;

export type ExportPermissionControllerAllPermissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportPermissionControllerAllPermissions>>
>;
export type ExportPermissionControllerAllPermissionsQueryError = unknown;

export const useExportPermissionControllerAllPermissions = <
  TError = unknown,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof exportPermissionControllerAllPermissions>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() =>
      isEnabled ? getExportPermissionControllerAllPermissionsKey() : null);
  const swrFn = () => exportPermissionControllerAllPermissions(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
