---
config:
  theme: redux
---
sequenceDiagram
    actor Admin
    participant PermissionService as Permission Service
    participant System
    participant CacheService as Cache Service
    participant Database

    Note over Admin: Admin View Flow
    Admin->>System: Browser a Manage Items, Assets, LOC, ...
    System->>PermissionService: Check if Admin logged in
    PermissionService-->>System: Response
    alt Admin not logged in
        System->>Admin: Notify error, redirect to login page
        Note over Admin: End (Error)
    else Admin logged in
        Note over Admin,CacheService: Query Cache Sub-process
        
        System->>CacheService: Query Cache
        
        alt Cache Hit
            CacheService-->>System: Return cached data
        else Cache Miss
            System->>Database: Query data
            Database-->>System: Data
            System->>CacheService: Cache set
            CacheService-->>System: Cache set success
        end
        
        System->>Admin: Display data
        Note over Admin: End (Success)
    end
